### ISSUE TITLE
Not working with angular 1.3.0.rc.3

### ISSUE THREAD

**Issue by LeleDev** [cgross/angular-busy#44]
With angular 1.3.0.rc.3 I get the following error:

```
TypeError: Cannot read property '$$state' of undefined
    at Uc.d.then (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.3/angular.min.js:107:139)
    at d (file:///mnt/Partizione1/Lele/Lavoro/Github%20projects/k2hire/bower_components/angular-busy/dist/angular-busy.min.js:1:940)
    at file:///mnt/Partizione1/Lele/Lavoro/Github%20projects/k2hire/bower_components/angular-busy/dist/angular-busy.min.js:1:349
    at Object.r [as forEach] (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.3/angular.min.js:7:298)
    at Object.c.reset (file:///mnt/Partizione1/Lele/Lavoro/Github%20projects/k2hire/bower_components/angular-busy/dist/angular-busy.min.js:1:294)
    at file:///mnt/Partizione1/Lele/Lavoro/Github%20projects/k2hire/bower_components/angular-busy/dist/angular-busy.min.js:1:2252
    at Object.fn (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.3/angular.min.js:117:127)
    at k.$digest (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.3/angular.min.js:118:250)
    at k.$apply (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.3/angular.min.js:121:264)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.3/angular.min.js:18:101 angular.js:10683(anonymous function) angular.js:10683(anonymous function) angular.js:7858k.$digest angular.js:13292k.$apply angular.js:13540(anonymous function) angular.js:1483e angular.js:4112d angular.js:1481ic angular.js:1501xd angular.js:1395(anonymous function) angular.js:24696j jquery.min.js:2k.fireWith jquery.min.js:2n.extend.ready jquery.min.js:2I jquery.min.js:
```

It works fine instead with angular 1.2.25

**Comment by marcelorl** [comment]
Hi,

I had the same issue again with angular 1.4.8, then I implemented @kaifer solution and it worked smoothly. Could you please pull his solution to the project?

Thanks.

**Comment by orcunland** [comment]
Hi,

I am now experiencing the same problem with **AngularJS 1.6.4** after upgrading my Angular version from **1.2.16**.
I am using **bower 1.8.0** version.
